[build-system]
requires = ["scikit-build-core>=0.10", "nanobind>=2.2.0"]
build-backend = "scikit_build_core.build"

[project]
name = "sultan-core-android"
version = "1.4.4.android1"
requires-python = ">=3.11,<3.12"

[tool.scikit-build]
cmake.version = ">=3.22"
cmake.build-type = "Release"
wheel.packages = ["src/sultan_core_android/python"]
